### ISSUE TITLE
谁会傻到现在去训练，血坑！！！

### ISSUE THREAD

**Issue by sunhaha123** [Tencent/HunyuanDiT#106]
readme里根本不写cuda版本，配好发现了根本运行不了。还要24g显存

**Comment by zml-ai** [comment]
Hi, we recommend CUDA versions 11.7 and 12.2. Training LoRa requires 24G of VRAM due to our 1.5B model and its 1024 resolution output. We’re working on optimizing VRAM usage for training, so stay tuned.
