### ISSUE TITLE
能否支持lora，controlnet这些？

### ISSUE THREAD

**Issue by yijinsheng** [Tencent/HunyuanDiT#11]
如题

**Comment by weponcn** [comment]
理论上sd支持的插件都支持 比如controlnet、lora

**Comment by yijinsheng** [comment]
> 理论上sd支持的插件都支持 比如controlnet、lora

应该也是基于diffusion的模型去实现的，就是不知道怎么去接入这些，如果能用在comfui里面就好了

**Comment by zml-ai** [comment]
We will subsequently open up adapters such as ControlNet and LoRa. 
We also welcome everyone to adapt on their own, and you can discuss any issues encountered during the adaptation process at any time.

**Comment by zml-ai** [comment]
#105
