### ISSUE TITLE
"ema", "module", "distill"这三种模型有什么区别，哪个质量最好

### ISSUE THREAD

**Issue by wodsoe** [Tencent/HunyuanDiT#110]
"ema", "module", "distill"这三种模型有什么区别，哪个质量最好？

**Comment by zml-ai** [comment]
If you value quality, choose the EMA model. If performance matters more, go for the distillation model. We’ve halved the inference steps in the EMA model using distillation. So, if the EMA takes 50 steps to infer, the distillation model can do the similarity in just 25.

**Comment by eesly** [comment]
What are the differences between the three models？
