### ISSUE TITLE
在comfyui中怎么使用controlnet

### ISSUE THREAD

**Issue by smae08** [Tencent/HunyuanDiT#113]
在comfyui中怎么使用controlnet，麻烦能提供个演示工作流吗

**Comment by xuhuaren** [comment]
we will support it and release code around 6.30.

**Comment by h3clikejava** [comment]
Now is 7.9.

**Comment by xuhuaren** [comment]
https://github.com/Tencent/HunyuanDiT/blob/main/comfyui-hydit/workflow/workflow_lora_controlnet.json

**Comment by CNEA-lw** [comment]
> https://github.com/Tencent/HunyuanDiT/blob/main/comfyui-hydit/workflow/workflow_lora_controlnet.json
Hello, I just tested three links. There are problems with the parameters of the links and some related nodes are missing. and cannot run.
![screenshot-20240710-123529](https://github.com/Tencent/HunyuanDiT/assets/164863967/7b5b8c7c-77ec-48ad-9cc6-4b9712aefca5)

**Comment by smae08** [comment]
> > https://github.com/Tencent/HunyuanDiT/blob/main/comfyui-hydit/workflow/workflow_lora_controlnet.json
> > Hello, I just tested three links. There are problems with the parameters of the links and some related nodes are missing. and cannot run.
> > ![screenshot-20240710-123529](https://private-user-images.githubusercontent.com/164863967/347258306-7b5b8c7c-77ec-48ad-9cc6-4b9712aefca5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1ODc4OTMsIm5iZiI6MTcyMDU4NzU5MywicGF0aCI6Ii8xNjQ4NjM5NjcvMzQ3MjU4MzA2LTdiNWI4YzdjLTc3ZWMtNDhhZC05Y2M2LTRiOTcxMmFlZmNhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQwNDU5NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYWZhNTc0NjBhNGEyMTVjMjU5NDIyN2UzZWM2ZDQyNTIyMjcwMWM4Njg2OGE5Y2Y3YjVhNzRjZTI3MmFhNjYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L7DoSC3h6FcgGXrgPWwIXPgQFqq0r9IXVVXzVrL0eg0)

https://github.com/Tencent/HunyuanDiT/tree/main/comfyui-hydit

你得安装这个节点啊

You need to install this node

**Comment by CNEA-lw** [comment]
> > > https://github.com/Tencent/HunyuanDiT/blob/main/comfyui-hydit/workflow/workflow_lora_controlnet.json
> > > 你好，我刚刚测试了三个链接，发现链接的参数有问题，缺少一些相关节点，无法运行。
> > > ![屏幕截图-20240710-123529](https://private-user-images.githubusercontent.com/164863967/347258306-7b5b8c7c-77ec-48ad-9cc6-4b9712aefca5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1ODc4OTMsIm5iZiI6MTcyMDU4NzU5MywicGF0aCI6Ii8xNjQ4NjM5NjcvMzQ3MjU4MzA2LTdiNWI4YzdjLTc3ZWMtNDhhZC05Y2M2LTRiOTcxMmFlZmNhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQwNDU5NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYWZhNTc0NjBhNGEyMTVjMjU5NDIyN2UzZWM2ZDQyNTIyMjcwMWM4Njg2OGE5Y2Y3YjVhNzRjZTI3MmFhNjYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L7DoSC3h6FcgGXrgPWwIXPgQFqq0r9IXVVXzVrL0eg0)
> 
> https://github.com/Tencent/HunyuanDiT/tree/main/comfyui-hydit
> 
> 你能安装这个节点吗？
> 
> 您需要安装此节点

感谢

**Comment by zml-ai** [comment]
#188
