### ISSUE TITLE
How to Use Saved Checkpoints to Generate Images?

### ISSUE THREAD

**Issue by iamwangyabin** [Tencent/HunyuanDiT#116]
After fully fine-tuning, I can get the following weights from the log directory:
mp_rank_00_model_states.pt
zero_pp_rank_0_mp_rank_00_optim_states.pt
How should I use these weights?

**Comment by zml-ai** [comment]
See https://github.com/Tencent/HunyuanDiT?tab=readme-ov-file#full-parameter-training
