### ISSUE TITLE
torch version issue

### ISSUE THREAD

**Issue by sahilqure** [Tencent/HunyuanDiT#119]
ModuleNotFoundError: No module named 'torch._six'
Using CUDA 12.1
Can u update the repo for latest CUDA

**Comment by zml-ai** [comment]
Hi, we provide Dockers for CUDA 11/12, which you can use to simplify environment installation. 
For more details, please see: https://github.com/Tencent/HunyuanDiT?tab=readme-ov-file#installation-guide-for-linux
