### ISSUE TITLE
Unclear lora training documentation

### ISSUE THREAD

**Issue by storyicon** [Tencent/HunyuanDiT#125]
I think the documentation for Lora training is unclear now. 
For example, `dataset/porcelain/jsons/porcelain.json` is mentioned in many places, but this file does not exist. Users who want to understand the data structure of this file can only look at the code. 
If the documents and tools are bad, I think the ecological prosperity will be blocked.

**Comment by yuanhaoliang** [comment]
you should use this command line:
```bash
 idk base -c dataset/yamls/porcelain.yaml -t dataset/porcelain/jsons/porcelain.json
```
transform porcelain.yaml to porcelain.json

**Comment by zml-ai** [comment]
Hi, we suggest adopting [IndexKits](https://github.com/Tencent/HunyuanDiT/tree/main/IndexKits) for data management, Arrow for data formatting, YAML for data preprocessing, and JSON for training script input. 

Please refer to the [README](https://github.com/Tencent/HunyuanDiT/tree/main?tab=readme-ov-file#data-preparation) for comprehensive data preparation guidelines.
