### ISSUE TITLE
Hope to know the details of the DialogGen paper appendix part.

### ISSUE THREAD

**Issue by KazusaKitakawa** [Tencent/HunyuanDiT#129]
Hi! Sincerely appreciate for all your team contributions. When read the paper of DialogGen(https://arxiv.org/pdf/2403.08857v1), I found that a reference to an appendix in this paper, but I can't find the appendix in the end of paper. Where can I get more information about this part content of this paper? Thx.

**Comment by yestinl** [comment]
@KazusaKitakawa Thanks! Actually we have uploaded the complete content, but there are some wrong reference, thanks for pointing it out. We have revised the paper and upload it to arxiv(https://arxiv.org/abs/2403.08857), you can download it again. If you have any questions, feel free to reopen this issue.
