### ISSUE TITLE
[BUG]使用v1.2版本的权重和v1.2的distill权重进行推理生成的图片全黑

### ISSUE THREAD

**Issue by GenerallyCovetous** [Tencent/HunyuanDiT#160]
**注意**

在复现的问题中，通常有以下几种常见情况：

1. 使用提供的配置复现模型库中的模型
2. 在其他数据集（例如自定义数据集）上复现模型库中的模型
3. 实现自定义模型，但利用的都是HunyuanDiT中实现的组件
4. 使用自己实现的新模块实现自定义模型

针对不同情况需要做的事情如下：

- 对于情况 1 和 3，请按照以下部分的步骤操作，以便我们快速识别问题。
- 对于情况 2 和 4，请理解我们无法提供太多帮助，因为我们通常不了解全部代码，用户应对自己编写的代码负责。
- 针对情况 2 和 4 的一个建议是，用户应首先检查错误是否在自实现代码中或原始代码中。例如，用户可以首先确保相同的模型在支持的数据集上运行良好。如果您仍然需要帮助，请描述您所做的工作和遇到的问题，并按照以下部分的步骤尽可能清晰地描述，以便我们更好地帮助您。

**检查清单**

1. 我已搜索相关问题，但无法获得预期的帮助。
2. 最新版本中尚未修复此问题。

**描述问题**

使用hunyuanDiT-main的代码仓运行sample_t2i.py运行hunyuanDiT v1.2出来的结果黑屏，使用v1.2的distill方法运行同样黑屏。使用hf上hunyuanDiT版本权重能够正常推理结果.

**重现步骤**

```none
python sample_t2i.py --infer-mode torch --prompt "渔舟唱晚"  --model-root /root/hunyuanDiT_files/v1_2 --no-enhance --beta-end 0.03   图片全黑
python sample_t2i.py --infer-mode torch --prompt "渔舟唱晚"  --model-root /root/hunyuanDiT_files/main --no-enhance --beta-end 0.03   图片正常
```

2. 您运行的配置目录是什么？

```none
如上
```

3. 您是否对代码或配置进行了任何修改？您是否理解您所修改的内容？
无
4. 您使用了什么数据集？
无
**环境**

1. 请运行 python utils/collect_env.py 收集必要的环境信息并粘贴在此。
sys.platform: linux
Python: 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:53:27) [GCC 9.4.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GCC: gcc (GCC) 7.3.0
PyTorch: 2.1.0
PyTorch compiling details: PyTorch built with:
  - GCC 10.2
  - C++ Version: 201703
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - Build settings: BLAS_INFO=open, BUILD_TYPE=Release, CXX_COMPILER=/opt/rh/devtoolset-10/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=open, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.0, USE_CUDA=ON, USE_CUDNN=OFF, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.16.0
OpenCV: 4.8.0
2. 您可以添加其他有助于定位问题的信息，例如
   - 您如何安装的 PyTorch \[例如，pip, conda, source\]
   - 其他可能相关的环境变量 (例如 `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH` 等)

**结果**
无
如果适用，请在此粘贴相关结果，例如，您的预期结果和实际结果。

```none
无
```

**Bug修复**
无
如果您已经确定了原因，可以在此提供信息。如果您愿意创建 PR 进行修复，也请在此留言，我们将不胜感激！

**Comment by seahunter4** [comment]
遇到了同样的问题

**Comment by sp1cae** [comment]
same error with torch

**Comment by zml-ai** [comment]
#214
