### ISSUE TITLE
官方COMFYUI的CN节点和DIFFSUERS的PIP节点冲突怎么解决？

### ISSUE THREAD

**Issue by slash1224** [Tencent/HunyuanDiT#179]
![微信图片_20240728100706](https://github.com/user-attachments/assets/0c3b918b-e0ca-44ef-bdd7-730032b9487d)
![微信图片_20240728100725](https://github.com/user-attachments/assets/7c47d4cd-c256-42ee-b8cd-632ee389c096)

装好了官方CN工作流需要的节点 则DIUFFSURESPIP节点出错 装好了 DIUFFSURE PIP节点则官方的节点出错 完全不懂怎么回事。COMFY版本已经退回了指点版本

**Comment by zml-ai** [comment]
#188
