### ISSUE TITLE
About comfyui clone, and controlnet in comfy

### ISSUE THREAD

**Issue by YacratesWyh** [Tencent/HunyuanDiT#188]
我注意到https://github.com/Tencent/HunyuanDiT/tree/main/comfyui-hydit 中使用cp rm的方法来操作，这样是不是不能实时更新git pull， 是否新建一个子库？

**Comment by YacratesWyh** [comment]
Anyway I cannot use controlnet in the official repo, and comfyui-hydit is difficult to maintain as it's requesting a lot more models not consistent to the setting of comfy.

**Comment by zml-ai** [comment]
ComfyUI officially supports the controlnet and lora of HuanYuan Dit, please feel free to use them.
https://github.com/comfyanonymous/ComfyUI
See workflows: https://github.com/Tencent/HunyuanDiT/tree/main/comfyui
