### ISSUE TITLE
Why the size of lora-tuning weights file is only 4k?

### ISSUE THREAD

**Issue by Young1993** [Tencent/HunyuanDiT#212]
I just followed the command 
`PYTHONPATH=./ sh lora/train_lora.sh --index-file dataset/porcelain/jsons/porcelain.json`

and finished the training. 

I see the lora-tuning weights file supplied by https://huggingface.co/Tencent-Hunyuan/HYDiT-LoRA/tree/main/porcelain is [92.3 MB](https://huggingface.co/Tencent-Hunyuan/HYDiT-LoRA/resolve/main/porcelain/adapter_model.safetensors?download=true)
![image](https://github.com/user-attachments/assets/3159354c-17bb-448a-9ed3-d180208f0e01)

But, my /log_EXP/001-lora_porcelain_ema_rank64/checkpoints is only 4k?

![image](https://github.com/user-attachments/assets/4eab5bfa-4551-49ae-9e5d-9dd6ecee9054)

Thus, is right?

**Comment by zml-ai** [comment]
First, you can check the weights of the lora to see if there are valid values. Second, safetensors will save more information about the model.
