### ISSUE TITLE
How much training data was used to train Hunyuan DiT?

### ISSUE THREAD

**Issue by omrastogi** [Tencent/HunyuanDiT#213]
First of all, congratulations on your outstanding work! The results are quite elegant.

I am considering training the Hunyuan DiT for a different task. However, to effectively evaluate its performance, I need to know the **exact number of image samples the model was trained** on.

I reviewed your paper, and while the dataset composition is well-detailed, I couldn't find the specific number of samples used during training.

Thank you for your time and assistance.

**Comment by zml-ai** [comment]
Hi, we used billions of data for pre-training and tens of millions of data for fine-tuning.
