### ISSUE TITLE
给的sample_t2i.py跑出的结果为什么和文章里面的结果对应不上

### ISSUE THREAD

**Issue by cugzhengzhimin** [Tencent/HunyuanDiT#23]
文章的结果可以跑出真实的人物，但是给的demo跑出的图均偏卡通，虽然语义是对的，文章中的那个权重是不是没有开放，希望可以写详细一点。

**Comment by lanson07** [comment]
same question

**Comment by icelighting** [comment]
too

**Comment by zml-ai** [comment]
Hi, please try using it with the Prompt Enhancement Model, you’ll get interesting results.

**Comment by lanson07** [comment]
> Hi, please try using it with the Prompt Enhancement Model, you’ll get interesting results.

Hi，I have tried the Prompt Enhancement Model, but the results are still not aligned with the paper and demo

Is the parameter weight  currently available the latest？

**Comment by yestinl** [comment]
@cugzhengzhimin 你可以尝试用”摄影风格“来指定生成图片的风格
You can try to use "Photography Style" to specify the style of generated images.
