### ISSUE TITLE
图片质量比SDXL不差，但是怎么生成文字？比 sd3 还是不行

### ISSUE THREAD

**Issue by wodsoe** [Tencent/HunyuanDiT#27]
图片质量比SDXL不差，但是怎么生成文字？比 sd3 还是不行啊

**Comment by liangwq** [comment]
这个应该内训练过，后面给予ocr图、海报、生成一些带文字图sft效果就会上来
你有兴趣可以自己试试，有很多开源数据的

**Comment by Jarvis73** [comment]
由于混元DiT是针对中英文双语场景训练的模型，目前中文文字渲染仍然是一个难题，我们还在探索和优化中，未来的版本中我们会增加中英文渲染的能力。

该 issue 与 #25 重复，这里将先关闭。如果还有其他疑问欢迎随时交流。
