### ISSUE TITLE
在哪里可以试用多轮对话生成图片？

### ISSUE THREAD

**Issue by chenbaiyujason** [Tencent/HunyuanDiT#3]

**Comment by wangyang0210** [comment]
https://image.hunyuan.tencent.com/authorize

需申请排队

**Comment by wangyang0210** [comment]
https://hunyuan.tencent.com/bot/chat
v1直接混元就行了

https://image.hunyuan.tencent.com/authorize

v2版本需申请排队

**Comment by wangyang0210** [comment]
<img width="846" alt="image" src="https://github.com/Tencent/HunyuanDiT/assets/36377605/df4f4054-82e0-48bb-a1de-bbe97f90526f">

**Comment by yestinl** [comment]
> https://hunyuan.tencent.com/bot/chat v1直接混元就行了
> 
> https://image.hunyuan.tencent.com/authorize
> 
> v2版本需申请排队

Thanks @wangyang0210 for the reply! That's correct. You can directly use multi-turn text interactions to generate the image by [Tencent Hunyuan Bot](https://hunyuan.tencent.com/bot/chat). We will also provide a multi-turn T2I (Text-to-Image) generation Gradio demo soon.

**Comment by Cerf-Volant425** [comment]
> > https://hunyuan.tencent.com/bot/chat v1直接混元就行了
> > https://image.hunyuan.tencent.com/authorize
> > v2版本需申请排队
> 
> Thanks @wangyang0210 for the reply! That's correct. You can directly use multi-turn text interactions to generate the image by [Tencent Hunyuan Bot](https://hunyuan.tencent.com/bot/chat). We will also provide a multi-turn T2I (Text-to-Image) generation Gradio demo soon.

Thanks for your great work. I only found the instructions for text2img. And I noticed you hava already uploaded the dialoggen model to the huggingface, I was wondering whether there are instructions for multi-round dialogue of this model. Or I should wait for the test of hunyuan_v2.

**Comment by yestinl** [comment]
@Cerf-Volant425  As  described in [Readme](https://github.com/Tencent/HunyuanDiT?tab=readme-ov-file#-tencent-hunyuan-bot), you can modify the image through continuous language interaction in [Tencent Hunyuan Bot](https://hunyuan.tencent.com/bot/chat). Here's an example:
![image](https://github.com/Tencent/HunyuanDiT/assets/27557933/79beb608-d4bd-4882-a851-ce17dc542eaa). 

Thank you for your suggestions. We will update the run commands and any other instructions for DialogGen later.

**Comment by yestinl** [comment]
@wangyang0210 @chenbaiyujason 最新新闻，我们提供了多轮对话绘图的demo.你可以通过以下命令来运行：
(Latest news, we provide a demo of multi-turn dialogue drawing. You can run it with the following command:)

```python
# Start a multi-turn T2I generation UI. 
# If your GPU memory is less than 32GB, use '--load-4bit' to enable 4-bit quantization, which requires at least 22GB of memory.
python app/multiTurnT2I_app.py
```

如果有任何其他问题，随时可以重新开启这个issue.
(If you have any other questions, you can reopen this issue at any time.)
