### ISSUE TITLE
“dialoggen/dialoggen_demo.py”功能阉割，你们会开源完整版的多轮对话功能么？

### ISSUE THREAD

**Issue by xiexiaoshinick** [Tencent/HunyuanDiT#30]
看了你们的“dialoggen/dialoggen_demo.py”代码，总感觉你们阉割了多轮对话的功能，现在只能用来完善提示词，接下来有开源完整多轮对话的demo计划么？

**Comment by Jiangfeng-Xiong** [comment]
In response to your query, please refer to the response provided in #3 for additional information, as it is the same issue. Thank you.

**Comment by yestinl** [comment]
@xiexiaoshinick 最新更新，我们提供了多轮对话绘图的demo.你可以通过以下命令来运行：
(Latest news, we provide a demo of multi-turn dialogue drawing. You can run it with the following command:)

```python
# Start a multi-turn T2I generation UI. 
# If your GPU memory is less than 32GB, use '--load-4bit' to enable 4-bit quantization, which requires at least 22GB of memory.
python app/multiTurnT2I_app.py
```

如果有任何其他问题，随时可以重新开启这个issue.
(If you have any other questions, feel free to reopen this issue at any time.)
