### ISSUE TITLE
关于app推理里的seed设置

### ISSUE THREAD

**Issue by StevenGao6** [Tencent/HunyuanDiT#32]
Thanks for your error report and we appreciate it a lot.

目前设置的seed范围为0-2^32-1，好像是设置不了-1随机种子

**Comment by flysssss** [comment]
修改一下hydit_app.py源文件，设置一个随机数，random.randint(1, 1_000_000_000)，每次生成时采用随机数做seed。可以界面上用Checkbox当开关控制，这样也能手动输入。

**Comment by yestinl** [comment]
@flysssss 感谢你的回复. @StevenGao6 你确实可以通过更改hydit_app.py源文件来实现种子的自定义设置。如果你还有问题的话，可以随时重新开启这个issue.

@flysssss Thanks for your reply. @StevenGao6 You can indeed customize the seed by changing the hydit_app.py source file. If you still have questions, you can reopen this issue at any time.
