### ISSUE TITLE
腾讯什么时候正大方了？

### ISSUE THREAD

**Issue by sjzsbgwb** [Tencent/HunyuanDiT#4]

**Comment by TencentWangTao** [comment]
目前主要的文生图开源社区依然主要基于U-Net架构模型进行开发，潜力巨大的中文DiT架构在开源社区仍然存在一定的空白。
腾讯混元文生图团队，与Sora、Stable Diffusion等团队不谋而合，率先探索了基于DiT架构的视觉生成模型，实测效果属于开源社区领先水平。
我们选择将最新的研究成果进行开源，让行业在更高的台阶上研发与发展，也希望能为基于DiT架构的文生图开源生态贡献属于腾讯的力量。同时，混元文生图是首个中文原生的DiT模型，具备中英文双语理解及生成能力，会在开源生态、及相关数据集中注入更多的中文元素，可以更好地满足中国企业和开发者的需求。

Currently, the major text-to-image open source community primarily develops models based on the U-Net architecture. There remains a significant gap in the open-source community for the promising DiT architecture, especially for Chinese applications.
Tencent Hunyuan text-to-image team, in alignment with teams like Sora and Stable Diffusion, has pioneered the exploration of vision generation models based on the DiT architecture. Our practical results demonstrate that our models are at the forefront of the open-source community.
We have chosen to open source our latest research achievements to elevate the industry's development and contribute Tencent's efforts to the text-to-image open-source ecosystem based on the DiT architecture. Moreover, Hunyuan's text-to-image model is the first native Chinese DiT model, with bilingual understanding and generation capabilities in both Chinese and English. This will enrich the open-source ecosystem and related datasets with more Chinese elements, better meeting the needs of Chinese enterprises and developers.

**Comment by fengweipeng** [comment]
我要像腾讯这么有钱，早就搞中文绘图模型了！中文是最简洁高效的语言，最适合ai学习。英文的分词表，少于2万，根本就没法用。光是周一到周日，一月到十二月，三角形、四边形、五边形、八边形就要独占20多个个词元，还有猪肉、牛肉、羊肉又是一堆的词元，ai就算把它们全都学会了，但是，还是不会说鳄鱼肉、狮子肉，7边形。这样练出来的ai不是人工智能，是人工智障！中文分词表，3500个就够用了，不仅简洁，而且易懂，ai很容易就能掌握中文的规律。中文训练的模型，可以很明确的告诉你“只有十二月，没有十三月”，但是，英文训练的模型根本不理解什么是十三月。只有中文才能训练出真正的人工智能！
