### ISSUE TITLE
看着需要40来G显存，后续有优化版吗

### ISSUE THREAD

**Issue by lonngxiang** [Tencent/HunyuanDiT#42]

**Comment by Jarvis73** [comment]
感谢关注我们的工作. 我们正在加速优化显存占用, 以适配显存更小的消费级显卡. 
作为临时方案, 您可以选择关闭 prompt 增强功能 (设置 --no-enhance 参数) 来快速试用文生图能力. 但是请注意, 缺乏 prompt 增强时的文生图能力可能会有一定的损失, 这取决于您输入 prompt 的范式. 

Thanks for paying attention to our work. We are accelerating the optimization of memory usage to adapt to consumer GPUs with smaller memory. 
As a temporary solution, you can choose to turn off the prompt enhancement feature with (--no-enhance) to quickly try out the capabilities of Wenshengtu. Please note, the generation capability without prompt enhancement might suffer some loss, depending on the paradigm you input the prompt.

**Comment by yestinl** [comment]
最新更新，我们支持对DialogGen进行4-bit的量化，只需占用21G的显存即可体验我们完整的功能（prompt 增强+图像生成）。你可以用以下命令来加载4bit量化的DialogGen模型：
> python sample_t2i.py --prompt "渔舟唱晚"  --load-4bit

In the latest update, we now support 4-bit quantization for DialogGen, which only requires 21G of GPU memory to experience our full features (prompt enhancement + image generation). You can use the following command to load the 4-bit quantized DialogGen model:
> python sample_t2i.py --prompt "渔舟唱晚"  --load-4bit
