### ISSUE TITLE
how to run HunyuanDiT model locally with llama.cpp?

### ISSUE THREAD

**Issue by zhouwg** [Tencent/HunyuanDiT#43]
thanks for Tencent's amazing HunyuanDiT(it's very cool in "Hunyuan Assistant(aka 混元助手)" as a Wechat Mini App(aka Wechat Xiaochengxu or 微信小程序)).

1. could you provide tutorial to illustrate how to run HunyuanDiT model locally with [llama.cpp](https://github.com/ggerganov/llama.cpp)(similar to following tutorial:https://huggingface.co/01-ai/Yi-6B-Chat-8bits#quick-start---llamacpp)?

    or provide tutorial to illustrate how to run HunyuanDiT model locally with [Tencent's NCNN](https://github.com/Tencent/ncnn)?

2.  is there any plan to release a GPT-4o style model of the HunyuanDiT model(ASR, TTS, Text2Image, LLM......in a single HunyuanDiT model)?

thanks so much.

**Comment by yestinl** [comment]
@zhouwg Thanks!
1. Currently, we do not have plans to support llama.cpp. Developers are encouraged to configure it according to their needs. If you encounter any issues, feel free to discuss them here.
2. In the short term, we do not plan to support running NCNN locally, but it might be possible in the future.
3. In the long term, supporting more modalities in a single model is certainly the direction of future development. Tencent Hunyuan will continue to open-source more large models that benefit the industry, so please stay tuned.

Feel free to reopen the issue if you have further questions.

**Comment by zhouwg** [comment]
> @zhouwg Thanks!
> 
>     1. Currently, we do not have plans to support llama.cpp. Developers are encouraged to configure it according to their needs. If you encounter any issues, feel free to discuss them here.
> 
>     2. In the short term, we do not plan to support running NCNN locally, but it might be possible in the future.
> 
>     3. In the long term, supporting more modalities in a single model is certainly the direction of future development. Tencent Hunyuan will continue to open-source more large models that benefit the industry, so please stay tuned.
> 
> 
> Feel free to reopen the issue if you have further questions.

thanks for your detailed comments and the information is very useful.

and
 
thanks for your time.
