### ISSUE TITLE
What does the style embedding mean, why is a constant value?

### ISSUE THREAD

**Issue by icelighting** [Tencent/HunyuanDiT#48]
<img width="869" alt="image" src="https://github.com/Tencent/HunyuanDiT/assets/35771160/934ca612-ef41-46cc-a037-a076223427c6">

**Comment by zml-ai** [comment]
This issue appears to be the same as issue #51 . We will close this issue for now. If there are further questions, feel free to reopen it.

**Comment by icelighting** [comment]
thanks for your reply
