### ISSUE TITLE
关于推理速度

### ISSUE THREAD

**Issue by ziyaxuanyi** [Tencent/HunyuanDiT#50]
默认的推理采样步数是100，但是每一步采样速度很慢，比sd1.5/sdxl慢的多，导致生成图片很慢，生成一张图片需要1分半的时间
测试显卡是3090，没有使用flash-attn，这个是正常的吗
采样步数必须是100这么大吗，sd1.5/sdxl的20步生成质量是否会下降很多？我测试生成几张图片好像效果差不多

**Comment by zml-ai** [comment]
Hi, we recommend using flash-attn for inference, where the inference speed on a 3090 GPU is around 80 seconds. 

Excitingly, we’ve open-sourced the TensorRT version, which supports the 3090 series GPUs, and the inference speed can be further improved by 47%, according to our tests, to around 40 seconds. 

Additionally, feel free to infer with different samplers and sampling steps. The results might pleasantly surprise you.
