### ISSUE TITLE
training code will be open-sourced?

### ISSUE THREAD

**Issue by huxian0402** [Tencent/HunyuanDiT#51]
Very solid work. when the training code will be open-sourced? @Jarvis73 @tencent-adm @Jiangfeng-Xiong @zdxiao @hzlzh

**Comment by zml-ai** [comment]
Thanks! We’re in the midst of preparations and will be going open source pretty soon. Stay tuned!

**Comment by zml-ai** [comment]
Great effort! If you’re looking to extend its functionality, such as enhancing the model’s capability with portrait data, you can expand the style_embedding. Train the portrait embedding when sampling portrait data, and train the general embedding when sampling general data. We will soon open source the training code, so please stay tuned.
