### ISSUE TITLE
HYDiT-XL/2 模型会发布吗

### ISSUE THREAD

**Issue by FacePoluke** [Tencent/HunyuanDiT#52]
谢谢您的工作，我想在小一点的HYDiT-XL/2做一些探索工作，请问这个模型能开源吗

**Comment by zml-ai** [comment]
Yes, undoubtedly, if there is HYDiT-XL/2, it would be more meaningful for research in resource-constrained scenarios. We will open-source it in the future. Stay tuned.

**Comment by zml-ai** [comment]
Yes, if HYDiT-XL/2 proves to be more meaningful for research in resource-constrained scenarios, we will open-source it in the future. Stay tuned.
