### ISSUE TITLE
请问需要严格用requirements.txt文件的版本吗？为什么用这么旧的包呢？谢谢

### ISSUE THREAD

**Issue by equinox-sun** [Tencent/HunyuanDiT#53]
rt

**Comment by zmwv823** [comment]
不需要，去掉所有版本要求依然能跑通，建议自己改一下端口号(开魔法的时候会出问题)，顺便把分享关了。

**Comment by yestinl** [comment]
我们提供的环境版本已经过充分测试，确保可用性和稳定性。如果您能够自己配置环境并正常运行，当然也是可以的。不过，我们无法保证自己配置的环境不会影响性能，因此这方面可能需要您自行验证。

Our provided environment versions have been thoroughly tested to ensure usability and stability. If you can configure your own environment and it runs correctly, that is certainly acceptable. However, we cannot guarantee that a self-configured environment will not affect performance, so you may need to verify this yourself.
