### ISSUE TITLE
About AI artifacts.

### ISSUE THREAD

**Issue by JincanDeng** [Tencent/HunyuanDiT#67]
Hi, thanks for your interest work. The technial report mentions the evaluation metric named "AI artifacts". How to understand this metric? Any example for it?

**Comment by zml-ai** [comment]
The concept of “AI artifacts” is used to evaluate how an image appears to be AI-generated. For example, a high score is defined as having no discernible AI artifacts, resembling real photographs or screenshots from movies and TV shows. On the other hand, a low score is defined by: the depiction of real-world objects that completely defy logic and common understanding; written text that doesn’t resemble realistic handwriting at all; and the presence of obvious abnormalities in human or animal figures, such as disproportionate body parts.
