### ISSUE TITLE
Could you release the weight for the image encoder of bilingual CLIP model?

### ISSUE THREAD

**Issue by hqhQAQ** [Tencent/HunyuanDiT#69]
**Describe the feature**

**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when \[....\].
Ex2. There is a recent paper \[....\], which is very helpful for \[....\].

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by Jiangfeng-Xiong** [comment]
The weight of image encoder is included in [clip_text_encoder/pytorch_model.bin](https://huggingface.co/Tencent-Hunyuan/HunyuanDiT/blob/main/t2i/clip_text_encoder/pytorch_model.bin)
<img width="1446" alt="image" src="https://github.com/Tencent/HunyuanDiT/assets/18069771/8e231a2b-9cfb-4451-a7e1-7c06f6fead7d"> , model structure is Vit-Huge
