### ISSUE TITLE
多轮对话api

### ISSUE THREAD

**Issue by Readyou123** [Tencent/HunyuanDiT#74]
调用多轮对话的api，感觉调用一次就开启一次新对话，不能使用多轮对话吗？

**Comment by yestinl** [comment]
抱歉，这里说的开启一次新对话什么意思？ 运行 python app/multiTurnT2I_app.py之后，就可以开始多轮对话了

**Comment by Readyou123** [comment]
感谢回复，我的意思是调用api接口：api_name="/pipeline"，这样可以多轮对话吗？

**Comment by yestinl** [comment]
@Readyou123 抱歉，还是不太理解你这里的需求。能否给个更加具体的例子吗？你是希望怎么调用呢？

**Comment by Readyou123** [comment]
from gradio_client import Client

client = Client("")
result = client.predict(
		input_text="Hello!!",
		infer_steps=100,
		seed=666,
		image_size="正方形(square, 1024x1024)",
		api_name="/pipeline"
)
print(result)
就是像这样调用接口。

**Comment by yestinl** [comment]
这部分的话，你可以自己根据需求开发，我们暂时不会开发支持。我们目前实现多轮的逻辑是在同一对话中保持相同的种子，然后传入历史对话给DialogGen去处理。我想你可以尝试去拼接符合格式的历史对话进行输入，从而完成多轮对话。
