### ISSUE TITLE
支持inpainting功能吗？

### ISSUE THREAD

**Issue by Phoenix724** [Tencent/HunyuanDiT#75]
会考虑训练inpainting模型吗？或者会发布官方的inpainting推理代码吗？

**Comment by zml-ai** [comment]
We’re planning to support the inpainting feature in the future. Stay tuned!

**Comment by dawei03896** [comment]
+1

**Comment by zml-ai** [comment]
The current version is already supported, please refer to the [link](https://github.com/Tencent/HunyuanDiT?tab=readme-ov-file#-community-contribution-leaderboard).
