### ISSUE TITLE
希望开放multiTurnT2I_app.py中request_mllm函数，实现解读图片解读

### ISSUE THREAD

**Issue by gavid0124** [Tencent/HunyuanDiT#76]
我发现multiTurnT2I_app.py中request_mllm函数，在文件48行，但是无法调用，可否告知这个8080端口的服务怎么启用？
def request_mllm(server_url='http://0.0.0.0:8080',history_messages=[], question="画一个木制的鸟",image=""):

**Comment by gg22mm** [comment]
8080这个端口服务代码  在哪里开启？
