### ISSUE TITLE
画出的图像中有小红书的水印

### ISSUE THREAD

**Issue by gavid0124** [Tencent/HunyuanDiT#77]
见下面的两张图片：
![带小红书水印1](https://github.com/Tencent/HunyuanDiT/assets/8635721/5dec1023-588e-42d2-88cc-1af2556bfb15)
![带小红书水印2](https://github.com/Tencent/HunyuanDiT/assets/8635721/b3d4367f-0eb4-458f-86f5-c4702e0f74ff)

**Comment by zml-ai** [comment]
We’ll be releasing the open-source fix for the version weights shortly. Stay tuned!

**Comment by zml-ai** [comment]
We have fixed the bug, details can be found at [link](https://huggingface.co/Tencent-Hunyuan/HunyuanDiT-v1.1)
