### ISSUE TITLE
Are there any other methods for generating in one or more steps that support hyper sd? Can accelerate image generation, currently generating slower

### ISSUE THREAD

**Issue by libai-lab** [Tencent/HunyuanDiT#85]
Are there any other methods for generating in one or more steps that support hyper sd? Can accelerate image generation, currently generating slower

**Comment by DarkAlchy** [comment]
As a trainer I see a lot of possibilities with this, but if they can't fix this to not be this slow it isn't worth my time to mess with.  4090 with flash attn and I lose 5-8 it/s?  Unacceptably slow as non 4090 people will move on.

**Comment by zml-ai** [comment]
Yes，we are currently working on this.  We'll let you know as soon as we are ready.
