### ISSUE TITLE
更新train代码之后，把之前的tensorrt推理代码给覆盖了

### ISSUE THREAD

**Issue by Jimzhou82sub** [Tencent/HunyuanDiT#88]
如题，当前代码不支持tensorRT推理了

**Comment by zml-ai** [comment]
We have fixed the bug, details can be found at https://github.com/Tencent/HunyuanDiT/blob/main/hydit/inference.py#L18”

**Comment by Jimzhou82sub** [comment]
请问tensorRT后续会支持到int8 优化吗
