### ISSUE TITLE
使用gradio的hydit_app.py启动， 加载DialogGen模型时报错

### ISSUE THREAD

**Issue by huangzhike** [Tencent/HunyuanDiT#92]
**Describe the bug**

异常信息如下， Transformers版本已经是最新的了

ValueError: The checkpoint you are trying to load has model type `llava_mistral` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.

**Comment by yestinl** [comment]
请运行 python utils/collect_env.py 和 pip list 去打印完整的环境信息，以便我们能定位问题。
同时你也可以尝试采用我们推荐的环境安装方式来配置对应的环境。
