### ISSUE TITLE
Full download of checkpoints not possible. Stucking always on the same download point. Pls advice

### ISSUE THREAD

**Issue by zappazack** [Tencent/HunyuanDiT#93]
ownloading 't2i/sdxl-vae-fp16-fix/config.json' to 'models\hunyuan\ckpts\.huggingface\download\t2i\sdxl-vae-fp16-fix\config.json.a0fc2b4620b60f1e599418c4de1c3d5e45db875a.incomplete'█████████████████████  | 1.66G/1.71G [31:23<01:02, 885kB/s]
t2i/sdxl-vae-fp16-fix/config.json: 100%|██████████████████████████████████████████████████████| 631/631 [00:00<?, ?B/s]
Download complete. Moving file to models\hunyuan\ckpts\t2i\sdxl-vae-fp16-fix\config.json/5.00G [31:25<1:01:46, 896kB/s]
Downloading 't2i/sdxl-vae-fp16-fix/diffusion_pytorch_model.bin' to 'models\hunyuan\ckpts\.huggingface\download\t2i\sdxl-vae-fp16-fix\diffusion_pytorch_model.bin.37eb3e09ae1ce3d6891ddf809ca927b618e501091142cf07fdd9cd170e3a046f.incomplete'
pytorch_model.bin: 100%|███████████████████████████████████████████████████████████| 1.71G/1.71G [32:24<00:00, 880kB/s]
Download complete. Moving file to models\hunyuan\ckpts\dialoggen\openai\clip-vit-large-patch14-336\pytorch_model.bin/s]
Downloading 't2i/tokenizer/special_tokens_map.json' to 'models\hunyuan\ckpts\.huggingface\download\t2i\tokenizer\special_tokens_map.json.a8b3208c2884c4efb86e49300fdd3dc877220cdf.incomplete'            | 1.73G/6.07G [32:06<1:20:01, 903kB/s]
t2i/tokenizer/special_tokens_map.json: 100%|██████████████████████████████████████████████████| 125/125 [00:00<?, ?B/s]
Download complete. Moving file to models\hunyuan\ckpts\t2i\tokenizer\special_tokens_map.json335M [00:58<05:15, 894kB/s]
Downloading 't2i/tokenizer/tokenizer_config.json' to 'models\hunyuan\ckpts\.huggingface\download\t2i\tokenizer\tokenizer_config.json.a14356073e11a885074a7cdbddc749463cefd911.incomplete'                | 1.47G/15.0G [27:17<4:05:03, 918kB/s]
t2i/tokenizer/tokenizer_config.json: 100%|████████████████████████████████████████████████████| 559/559 [00:00<?, ?B/s]
Download complete. Moving file to models\hunyuan\ckpts\t2i\tokenizer\tokenizer_config.json
Downloading 't2i/tokenizer/vocab.txt' to 'models\hunyuan\ckpts\.huggingface\download\t2i\tokenizer\vocab.txt.6246906805d02aca01714c71e4c8d77b69a7a131.incomplete'
t2i/tokenizer/vocab.txt: 100%|██████████████████████████████████████████████████████| 317k/317k [00:00<00:00, 2.55MB/s]
Download complete. Moving file to models\hunyuan\ckpts\t2i\tokenizer\vocab.txt
Downloading 't2i/tokenizer/vocab_org.txt' to 'models\hunyuan\ckpts\.huggingface\download\t2i\tokenizer\vocab_org.txt.ca4f9781030019ab9b253c6dcb8c7878b6dc87a5.incomplete'
t2i/tokenizer/vocab_org.txt: 100%|███████████████████████████████████████████████████| 110k/110k [00:00<00:00, 607kB/s]
Download complete. Moving file to models\hunyuan\ckpts\t2i\tokenizer\vocab_org.txt
diffusion_pytorch_model.bin: 100%|███████████████████████████████████████████████████| 335M/335M [05:35<00:00, 996kB/s]
Download complete. Moving file to models\hunyuan\ckpts\t2i\sdxl-vae-fp16-fix\diffusion_pytorch_model.bin1:10, 1.03MB/s]
pytorch_model.bin: 100%|████████████████████████████████████████████████████████| 3.94G/3.94G [1:04:02<00:00, 1.02MB/s]
model-00003-of-00004.safetensors: 100%|█████████████████████████████████████████| 4.93G/4.93G [1:16:03<00:00, 1.08MB/s]
Download complete. Moving file to models\hunyuan\ckpts\dialoggen\model-00003-of-00004.safetensors04:11<14:16, 1.18MB/s]
model-00001-of-00004.safetensors: 100%|█████████████████████████████████████████| 4.94G/4.94G [1:16:12<00:00, 1.08MB/s]
Download complete. Moving file to models\hunyuan\ckpts\dialoggen\model-00001-of-00004.safetensors15:47<13:09, 1.43MB/s]
model-00002-of-00004.safetensors: 100%|█████████████████████████████████████████| 5.00G/5.00G [1:16:37<00:00, 1.09MB/s]
Download complete. Moving file to models\hunyuan\ckpts\dialoggen\model-00002-of-00004.safetensors15:59<11:33, 1.60MB/s]
pytorch_model_ema.pt: 100%|█████████████████████████████████████████████████████| 6.07G/6.07G [1:21:12<00:00, 1.25MB/s]
Download complete. Moving file to models\hunyuan\ckpts\t2i\model\pytorch_model_ema.pt1G/6.07G [1:16:21<07:52, 2.23MB/s]
Fetching 49 files:  69%|█████████████████████████████████████████▋                  | 34/49 [1:21:26<35:55, 143.71s/it]
pytorch_model.bin: 100%|████████████████████████████████████████████████████████| 15.0G/15.0G [1:38:53<00:00, 2.52MB/s]
Download complete. Moving file to models\hunyuan\ckpts\t2i\mt5\pytorch_model.bin
Traceback (most recent call last):███████                                     | 4.72G/15.0G [1:11:27<1:21:07, 2.11MB/s]
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen.bin:  38%|█████████████████████▍                                  | 5.74G/15.0G [1:16:17<42:40, 3.61MB/s]
    httplib_response = self._make_request(
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request100%|████████████████████████████████████████████████████████| 15.0G/15.0G [1:38:53<00:00, 7.08MB/s]
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py", line 1722, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(url=url, proxies=proxies, timeout=etag_timeout, headers=headers)
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py", line 1645, in get_hf_file_metadata
    r = _request_wrapper(
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py", line 372, in _request_wrapper
    response = _request_wrapper(
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py", line 395, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\utils\_http.py", line 66, in send
    return super().send(request, *args, **kwargs)
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: (ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')), '(Request ID: aee58ec5-dfa6-4ba0-a7cd-5c740cacae50)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\Scripts\huggingface-cli.exe\__main__.py", line 7, in <module>
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\commands\huggingface_cli.py", line 51, in main
    service.run()
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\commands\download.py", line 146, in run
    print(self._download())  # Print path to downloaded files
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\commands\download.py", line 180, in _download
    return snapshot_download(
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\_snapshot_download.py", line 294, in snapshot_download
    thread_map(
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\contrib\concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\contrib\concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\_snapshot_download.py", line 268, in _inner_hf_hub_download
    return hf_hub_download(
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py", line 1202, in hf_hub_download
    return _hf_hub_download_to_local_dir(
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py", line 1440, in _hf_hub_download_to_local_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py", line 1826, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

**Comment by C0nsumption** [comment]
> ownloading 't2i/sdxl-vae-fp16-fix/config.json' to 'models\hunyuan\ckpts.huggingface\download\t2i\sdxl-vae-fp16-fix\config.json.a0fc2b4620b60f1e599418c4de1c3d5e45db875a.incomplete'█████████████████████ | 1.66G/1.71G [31:23<01:02, 885kB/s] t2i/sdxl-vae-fp16-fix/config.json: 100%|██████████████████████████████████████████████████████| 631/631 [00:00<?, ?B/s] Download complete. Moving file to models\hunyuan\ckpts\t2i\sdxl-vae-fp16-fix\config.json/5.00G [31:25<1:01:46, 896kB/s] Downloading 't2i/sdxl-vae-fp16-fix/diffusion_pytorch_model.bin' to 'models\hunyuan\ckpts.huggingface\download\t2i\sdxl-vae-fp16-fix\diffusion_pytorch_model.bin.37eb3e09ae1ce3d6891ddf809ca927b618e501091142cf07fdd9cd170e3a046f.incomplete' pytorch_model.bin: 100%|███████████████████████████████████████████████████████████| 1.71G/1.71G [32:24<00:00, 880kB/s] Download complete. Moving file to models\hunyuan\ckpts\dialoggen\openai\clip-vit-large-patch14-336\pytorch_model.bin/s] Downloading 't2i/tokenizer/special_tokens_map.json' to 'models\hunyuan\ckpts.huggingface\download\t2i\tokenizer\special_tokens_map.json.a8b3208c2884c4efb86e49300fdd3dc877220cdf.incomplete' | 1.73G/6.07G [32:06<1:20:01, 903kB/s] t2i/tokenizer/special_tokens_map.json: 100%|██████████████████████████████████████████████████| 125/125 [00:00<?, ?B/s] Download complete. Moving file to models\hunyuan\ckpts\t2i\tokenizer\special_tokens_map.json335M [00:58<05:15, 894kB/s] Downloading 't2i/tokenizer/tokenizer_config.json' to 'models\hunyuan\ckpts.huggingface\download\t2i\tokenizer\tokenizer_config.json.a14356073e11a885074a7cdbddc749463cefd911.incomplete' | 1.47G/15.0G [27:17<4:05:03, 918kB/s] t2i/tokenizer/tokenizer_config.json: 100%|████████████████████████████████████████████████████| 559/559 [00:00<?, ?B/s] Download complete. Moving file to models\hunyuan\ckpts\t2i\tokenizer\tokenizer_config.json Downloading 't2i/tokenizer/vocab.txt' to 'models\hunyuan\ckpts.huggingface\download\t2i\tokenizer\vocab.txt.6246906805d02aca01714c71e4c8d77b69a7a131.incomplete' t2i/tokenizer/vocab.txt: 100%|██████████████████████████████████████████████████████| 317k/317k [00:00<00:00, 2.55MB/s] Download complete. Moving file to models\hunyuan\ckpts\t2i\tokenizer\vocab.txt Downloading 't2i/tokenizer/vocab_org.txt' to 'models\hunyuan\ckpts.huggingface\download\t2i\tokenizer\vocab_org.txt.ca4f9781030019ab9b253c6dcb8c7878b6dc87a5.incomplete' t2i/tokenizer/vocab_org.txt: 100%|███████████████████████████████████████████████████| 110k/110k [00:00<00:00, 607kB/s] Download complete. Moving file to models\hunyuan\ckpts\t2i\tokenizer\vocab_org.txt diffusion_pytorch_model.bin: 100%|███████████████████████████████████████████████████| 335M/335M [05:35<00:00, 996kB/s] Download complete. Moving file to models\hunyuan\ckpts\t2i\sdxl-vae-fp16-fix\diffusion_pytorch_model.bin1:10, 1.03MB/s] pytorch_model.bin: 100%|████████████████████████████████████████████████████████| 3.94G/3.94G [1:04:02<00:00, 1.02MB/s] model-00003-of-00004.safetensors: 100%|█████████████████████████████████████████| 4.93G/4.93G [1:16:03<00:00, 1.08MB/s] Download complete. Moving file to models\hunyuan\ckpts\dialoggen\model-00003-of-00004.safetensors04:11<14:16, 1.18MB/s] model-00001-of-00004.safetensors: 100%|█████████████████████████████████████████| 4.94G/4.94G [1:16:12<00:00, 1.08MB/s] Download complete. Moving file to models\hunyuan\ckpts\dialoggen\model-00001-of-00004.safetensors15:47<13:09, 1.43MB/s] model-00002-of-00004.safetensors: 100%|█████████████████████████████████████████| 5.00G/5.00G [1:16:37<00:00, 1.09MB/s] Download complete. Moving file to models\hunyuan\ckpts\dialoggen\model-00002-of-00004.safetensors15:59<11:33, 1.60MB/s] pytorch_model_ema.pt: 100%|█████████████████████████████████████████████████████| 6.07G/6.07G [1:21:12<00:00, 1.25MB/s] Download complete. Moving file to models\hunyuan\ckpts\t2i\model\pytorch_model_ema.pt1G/6.07G [1:16:21<07:52, 2.23MB/s] Fetching 49 files: 69%|█████████████████████████████████████████▋ | 34/49 [1:21:26<35:55, 143.71s/it] pytorch_model.bin: 100%|████████████████████████████████████████████████████████| 15.0G/15.0G [1:38:53<00:00, 2.52MB/s] Download complete. Moving file to models\hunyuan\ckpts\t2i\mt5\pytorch_model.bin Traceback (most recent call last):███████ | 4.72G/15.0G [1:11:27<1:21:07, 2.11MB/s] File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen.bin: 38%|█████████████████████▍ | 5.74G/15.0G [1:16:17<42:40, 3.61MB/s] httplib_response = self._make_request( File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request100%|████████████████████████████████████████████████████████| 15.0G/15.0G [1:38:53<00:00, 7.08MB/s] six.raise_from(e, None) File "", line 3, in raise_from File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 462, in _make_request httplib_response = conn.getresponse() File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1375, in getresponse response.begin() File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin version, status, reason = self._read_status() File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 287, in _read_status raise RemoteDisconnected("Remote end closed connection without" http.client.RemoteDisconnected: Remote end closed connection without response
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 486, in send resp = conn.urlopen( File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 799, in urlopen retries = retries.increment( File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 550, in increment raise six.reraise(type(error), error, _stacktrace) File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\packages\six.py", line 769, in reraise raise value.with_traceback(tb) File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen httplib_response = self._make_request( File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request six.raise_from(e, None) File "", line 3, in raise_from File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 462, in _make_request httplib_response = conn.getresponse() File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1375, in getresponse response.begin() File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin version, status, reason = self._read_status() File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 287, in _read_status raise RemoteDisconnected("Remote end closed connection without" urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py", line 1722, in _get_metadata_or_catch_error metadata = get_hf_file_metadata(url=url, proxies=proxies, timeout=etag_timeout, headers=headers) File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\utils_validators.py", line 114, in _inner_fn return fn(*args, **kwargs) File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py", line 1645, in get_hf_file_metadata r = _request_wrapper( File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py", line 372, in _request_wrapper response = _request_wrapper( File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py", line 395, in _request_wrapper response = get_session().request(method=method, url=url, **params) File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 703, in send r = adapter.send(request, **kwargs) File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\utils_http.py", line 66, in send return super().send(request, *args, **kwargs) File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 501, in send raise ConnectionError(err, request=request) requests.exceptions.ConnectionError: (ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')), '(Request ID: aee58ec5-dfa6-4ba0-a7cd-5c740cacae50)')
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code exec(code, run_globals) File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\Scripts\huggingface-cli.exe__main__.py", line 7, in File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\commands\huggingface_cli.py", line 51, in main service.run() File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\commands\download.py", line 146, in run print(self._download()) # Print path to downloaded files File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\commands\download.py", line 180, in _download return snapshot_download( File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\utils_validators.py", line 114, in _inner_fn return fn(*args, **kwargs) File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub_snapshot_download.py", line 294, in snapshot_download thread_map( File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\contrib\concurrent.py", line 69, in thread_map return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs) File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\contrib\concurrent.py", line 51, in _executor_map return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs)) File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\std.py", line 1181, in **iter** for obj in iterable: File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\concurrent\futures_base.py", line 621, in result_iterator yield _result_or_cancel(fs.pop()) File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\concurrent\futures_base.py", line 319, in _result_or_cancel return fut.result(timeout) File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\concurrent\futures_base.py", line 451, in result return self.__get_result() File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\concurrent\futures_base.py", line 403, in __get_result raise self._exception File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub_snapshot_download.py", line 268, in _inner_hf_hub_download return hf_hub_download( File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\utils_validators.py", line 114, in _inner_fn return fn(*args, **kwargs) File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py", line 1202, in hf_hub_download return _hf_hub_download_to_local_dir( File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py", line 1440, in _hf_hub_download_to_local_dir _raise_on_head_call_error(head_call_error, force_download, local_files_only) File "C:\Users\Intersurf\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py", line 1826, in _raise_on_head_call_error raise LocalEntryNotFoundError( huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.



You download the repo manually or just use git lfs to install. But ensure you are downloaing the most recent version:
https://huggingface.co/Tencent-Hunyuan/HunyuanDiT-v1.1

it should be in the ckpt dir you created. HunyuanDiT-v1.1 directory is essentially renamed to ckpt

**Comment by zappazack** [comment]
Thx but sadly getting now a so called subprocess error during installation will open a new issue
