### ISSUE TITLE
Will the code for implementing Distillation be released?

### ISSUE THREAD

**Issue by alxiang** [Tencent/HunyuanDiT#96]
I'm interested in fine-tuning a model and distilling it -- will the distillation code be released so I can distill the fine-tuned model?

**Comment by zml-ai** [comment]
Yes，we are currently working on this. We'll let you know as soon as we are ready.

**Comment by ChunChenLin** [comment]
Hi, @zml-ai 
Is the distillation code available now? Thanks :))
